### ISSUE TITLE
Organize/Refactor functions

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/VisuMorph#20]
As the team expressed interests in making our package to utilize OOP approach in development, we need to modify our existing functions' specifications to keep inline with this.

Additionally, we need to create a class i.e. `VisuMorph.Image` and provide basic docstrings to describe what it does for better interfacing between this and user-facing functions.

**Comment by SoloSynth1** [comment]
Also needs to update our `README.md` to include:

> - a summary paragraph that describes the project at a high level
> - a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)
> - a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).

As per requirements listed here: https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone1/milestone1.html

**Comment by atabak-alishiri** [comment]
> Also needs to update our `README.md` to include:
> 
> > * a summary paragraph that describes the project at a high level
> > * a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)
> > * a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).
> 
> As per requirements listed here: https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone1/milestone1.html

I can take care of updating the readme file.
