### ISSUE TITLE
Create a Release for Milestone 1

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/VisuMorph#28]

**Comment by SoloSynth1** [comment]
Closing this issue as a release has been created under the tag v0.0.1

**Comment by atabak-alishiri** [comment]
I did create the release, sorry I should have first added this to project

**Comment by SoloSynth1** [comment]
Yeah no worries, so I think now we are pretty set to go

I will create the documentation for our submission, thanks!
