### ISSUE TITLE
Write vignette for `scale` function

### ISSUE THREAD

**Issue by Marcony1** [UBC-MDS/VisuMorph#51]

**Comment by SoloSynth1** [comment]
- [ ] Defining the purposes of the functions
- [ ] Importing libraries
- [ ] Loading data
- [ ] Providing detailed explanations
- [ ] Displaying input images
- [ ] Codes for the actual transformation
- [ ] Displaying output images
- [ ] Summary

**Comment by SoloSynth1** [comment]
Closes by #60.
