### ISSUE TITLE
Make cookiecutter to refer to the markdown files in the root folder

### ISSUE THREAD

**Issue by Marcony1** [UBC-MDS/VisuMorph#55]

**Comment by atabak-alishiri** [comment]
@SoloSynth1, @Marcony1
Since it already refers to the markdown files, should we mark this issue resolved?

**Comment by SoloSynth1** [comment]
I will look into this issue once after I submit a PR for #50. Thanks!

**Comment by SoloSynth1** [comment]
I believe we still have to make some change on the ToC to include our examples as well as the things mentioned by Tiff on slack.

**Comment by SoloSynth1** [comment]
@atabak-alishiri I have created #62 for this, and it should resolve this issue. Please take a look on the PR. Thanks!
