### ISSUE TITLE
Manually publish to ReadTheDocs

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/VisuMorph#56]
Connect the GitHub repo to ReadTheDocs and manually publish at least once.

**Comment by SoloSynth1** [comment]
ReadTheDocs page registered and created:
https://readthedocs.org/projects/visumorph/

I will close this issue once we confirm the rendered website is OK.

**Comment by Marcony1** [comment]
I confirm it is ok!

**Comment by Marcony1** [comment]
I can see it. But I guess the content is missing

**Comment by SoloSynth1** [comment]
Should be resolved in the latest merge (#65)

This latest build passed (https://readthedocs.org/projects/visumorph/builds/23260082/)

@Marcony1  Can you help to check if [the site](https://visumorph.readthedocs.io/en/latest/) is rendered properly?

**Comment by atabak-alishiri** [comment]
@SoloSynth1 LGTM, Thank you.

**Comment by SoloSynth1** [comment]
Thanks! Closing this issue.
