### ISSUE TITLE
Create a CONTRIBUTORS.md

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/VisuMorph#6]

**Comment by SoloSynth1** [comment]
Did tiff updated the requirements? I am not seeing `CONTRIBUTORS.md` being mentioned in the [milestone 1 page ](https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone1/milestone1.html) anymore...

**Comment by SoloSynth1** [comment]
@Marcony1 Do you think we can close this issue?

**Comment by Marcony1** [comment]
Yes, I think she updated the instructions. Now the contributors should be listed in the Readme file. So, I believe we can close this one.

**Comment by SoloSynth1** [comment]
Oh yes I just saw the convo on Slack (https://ubc-mds.slack.com/archives/C24GEK3PV/p1704860185813519). Thanks for the confirmation!

Closing this issue.
