### ISSUE TITLE
Discussion on license of our package

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/VisuMorph#68]
Here is the issue for discussion of everything related to the license used for our package, as mandated by milestone 4's requirement.

**Comment by shawnhu444** [comment]
agreed on the changes

**Comment by atabak-alishiri** [comment]
Here is my suggestion and justification:

MIT License: This license is easy to understand and widely used for open-source projects. It lets people do a lot with your project, like using it for business, changing it, sharing it with others, and even allowing them to give permission to others to use it. They don't have to use the same license if they change your project and share it. Also, there are only a few rules about how to show copyright information.

**Comment by Marcony1** [comment]
I  would also agree with the MIT License in this case (although, we might still change it in the future if we find one that suits our project better). However, because of the level of our package, I don't think there will be any problem by using a license for open-source projects.

**Comment by SoloSynth1** [comment]
@atabak-alishiri @Marcony1 I think both of you raised really good points for keep using the MIT License. 

Personally, I would prefer GNU GPL v2/3, but compared to MIT, in this case I think it is adding unnecessary complication and limitation such as requiring the derived works to be only published under the same license. 

As this package is meant to be a learning example, a short and simple license only requiring preservation of our copyright and license notices (i.e. MIT License) would suffice.

**Comment by atabak-alishiri** [comment]
So, I believe we all agree on using the MIT license for our software. Since the package doesn't include creative content, we won't need a creative license, right?

**Comment by SoloSynth1** [comment]
I think so. Of course we can use CC licenses for our non-code components (i.e. documentations, but that's arguable as they are generated from source codes as well), but it seems like [CC do not recommend licensing software using their licenses](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

Also, from https://choosealicense.com/non-software/:

> ... Any open source software license or open license for media (see [above](https://choosealicense.com/non-software/#data-media-etc)) also applies to software documentation...

So, unless we have substantial contents in this project that is not related to the package itself, I would say there is no need for a second license.

Edit: typo

**Comment by SoloSynth1** [comment]
Closing this issue as all members unequivocally agreed to keep using the MIT License.
