### ISSUE TITLE
Addressing Dan Zhang's feedback: updating readme (examples and instructions)

### ISSUE THREAD

**Issue by atabak-alishiri** [UBC-MDS/VisuMorph#92]

**Comment by atabak-alishiri** [comment]
Here is the feedback:

The package overall is amazing and I have a lot of fun learning it. I really enjoyed trying it out and can see myself using it more. Just a couple of quick suggestions:

Installation Command: Maybe break up the big installation command into smaller steps? It could be easier to debug if something goes wrong.

Examples in the README: Good job on writing the detailed examples on your documentation site! It would be awesome if you could add a few simple ones in the README for quick reference.

Pytest Section: The pytest part in the README seems a bit isolated and simple. Maybe integrate it with other sections?

Installation Instructions: The current setup instructions seem more developer note. How about adding a straightforward command like pip or conda for regular users?

**Comment by SoloSynth1** [comment]
Linked to external issue https://github.com/UBC-MDS/software-review-2024/issues/18.
