### ISSUE TITLE
Increase test coverage for `scale`

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/VisuMorph#98]
As it stands, `scale` has a sub-100% test coverage. We got deducted marks on this so it would be best to ramp that number up.

**Comment by SoloSynth1** [comment]
From CodeCov:
https://app.codecov.io/github/UBC-MDS/VisuMorph/blob/main/src%2Fvisumorph%2Fscale.py

**Comment by atabak-alishiri** [comment]
@shawnhu444 would you be able to take care of this issue before the deadline?
